## With Keras

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import  StandardScaler

2024-07-28 13:08:41.365760: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-28 13:08:41.365858: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-28 13:08:41.495102: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.california_housing.load_data(
    version="large", path="california_housing.npz", test_split=0.2, seed=113
)

743530/743530 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
x_train.shape

(16512, 8)

In [4]:
x_train.dtype

dtype('float32')

In [5]:
x_train[0]

array([-118.27  ,   34.09  ,   52.    , 2327.    ,  555.    , 1048.    ,
        491.    ,    3.7847], dtype=float32)

In [6]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

y_train = (y_train - y_train.mean()) / y_train.std()
y_test = (y_test - y_train.mean()) / y_train.std()

In [7]:
x_train[0]

array([ 0.6457759 , -0.7209302 ,  1.8532751 , -0.14375815,  0.03619913,
       -0.3331862 , -0.02698459, -0.04505231], dtype=float32)

In [8]:
x_test[0]

array([ 0.60079885, -0.7256249 ,  1.2975911 , -0.20348448, -0.13276172,
       -0.1455231 , -0.11987179, -0.25494424], dtype=float32)

In [9]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  
])

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(
    optimizer='adam', 
    loss='mse',        
    metrics=['mae']     
)

In [12]:
model.fit(x_train, y_train, epochs=100, validation_split=0.2, batch_size=64)

Epoch 1/100
110/207 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6662 - mae: 0.6136

I0000 00:00:1722172137.990053      73 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


207/207 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 0.5602 - mae: 0.5537 - val_loss: 0.3097 - val_mae: 0.3978
Epoch 2/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3005 - mae: 0.3942 - val_loss: 0.2873 - val_mae: 0.3806
Epoch 3/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2657 - mae: 0.3676 - val_loss: 0.2789 - val_mae: 0.3750
Epoch 4/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2575 - mae: 0.3606 - val_loss: 0.2739 - val_mae: 0.3562
Epoch 5/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2592 - mae: 0.3576 - val_loss: 0.2670 - val_mae: 0.3724
Epoch 6/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2490 - mae: 0.3535 - val_loss: 0.2603 - val_mae: 0.3524
Epoch 7/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2491 - mae: 0.3531 - val_loss: 0.2542 - val_mae: 0.3440
Epoch 8/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2468 - mae: 0.3482 - val_loss: 0.2518 - val_mae: 0.3479
Epoch 9/100
207/207 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss:

## With Pytorch

In [13]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [14]:
num_epochs = 100
learning_rate = 0.001
device = "cuda" if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [15]:
class MyDataset(Dataset):
    def __init__(self, data, labels):
        self.data = torch.from_numpy(data).float()
        self.labels = torch.from_numpy(labels).float()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

In [16]:
train_data = MyDataset(x_train, y_train)
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)

In [17]:
    test_data = MyDataset(x_train, y_train)
    test_loader = DataLoader(train_data, batch_size=32, shuffle=True)

In [18]:
class NNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.net=nn.Sequential(
            nn.Linear(in_features=8, out_features=10),
            nn.ReLU(),
            nn.Linear(in_features=10, out_features=10),
            nn.ReLU(),
            nn.Linear(in_features=10, out_features=10),
            nn.ReLU(),
            nn.Linear(in_features=10, out_features=1),
        )
    def forward(self, x):
        return self.net(x)

In [19]:
model = NNet().to(device)
print(model)

NNet(
  (net): Sequential(
    (0): Linear(in_features=8, out_features=10, bias=True)
    (1): ReLU()
    (2): Linear(in_features=10, out_features=10, bias=True)
    (3): ReLU()
    (4): Linear(in_features=10, out_features=10, bias=True)
    (5): ReLU()
    (6): Linear(in_features=10, out_features=1, bias=True)
  )
)


In [20]:
def mae(loader):
    test_acc=0
    model.eval() 
    MAE = nn.L1Loss()

    with torch.no_grad(): 
        for i, (x, y) in enumerate(loader): 

            x = x.to(device) 
            y = y.to(device) 

            outputs = model(x) 
            mae_loss = MAE(outputs, y.unsqueeze(1)) 
  
    return mae_loss            

In [21]:
criterion = torch.nn.MSELoss() 
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [22]:
for epoch in range(num_epochs):    
    
    train_loss = 0
    model.train()
    
    for i, (x, y) in enumerate(train_loader):
        
        x = x.to(device)
        y = y.to(device)
        
        outputs = model(x)
        loss = criterion(outputs, y.unsqueeze(1))
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    
    mae_loss = mae(train_loader)
    
    print(f"Epoch {epoch+1}/{num_epochs}\tMAE Loss : {mae_loss}\tMSE Loss : {loss.item()}")

Epoch 1/100	MAE Loss : 0.5369888544082642	MSE Loss : 0.3800298571586609
Epoch 2/100	MAE Loss : 0.2778993546962738	MSE Loss : 0.604230523109436
Epoch 3/100	MAE Loss : 0.3159369230270386	MSE Loss : 0.2088800072669983
Epoch 4/100	MAE Loss : 0.36809998750686646	MSE Loss : 0.15023329854011536
Epoch 5/100	MAE Loss : 0.3568727970123291	MSE Loss : 0.3167200982570648
Epoch 6/100	MAE Loss : 0.2816064655780792	MSE Loss : 0.12637533247470856
Epoch 7/100	MAE Loss : 0.3880506753921509	MSE Loss : 0.2814302444458008
Epoch 8/100	MAE Loss : 0.47619110345840454	MSE Loss : 0.17073330283164978
Epoch 9/100	MAE Loss : 0.41422879695892334	MSE Loss : 0.5374760031700134
Epoch 10/100	MAE Loss : 0.31286728382110596	MSE Loss : 0.25085294246673584
Epoch 11/100	MAE Loss : 0.4474789500236511	MSE Loss : 0.24821311235427856
Epoch 12/100	MAE Loss : 0.3575958013534546	MSE Loss : 0.15350914001464844
Epoch 13/100	MAE Loss : 0.28333088755607605	MSE Loss : 0.24804723262786865
Epoch 14/100	MAE Loss : 0.34613436460494995	MSE L